import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { Session } from 'next-auth'
import AuthContext from './AuthContext';
import { GetServerSideProps } from 'next';

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch(`localhost:3000/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: Session
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext session={session}>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context.req.headers.cookie || '');
  return {
    props: {
      session,
    },
  };
};